#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Rui Suzuki
# SPDX-License=Identifier: BSD-3-Clause

data_name = ["SUZUKI","NAKAJI","HIRANO","KIKUTI"]
data_add = ["ruiszk@usomail.rs","ismooo@ramen.ff","butter@fly.dm","kikut@notrelated.cit"]

n = 0
cnt = 1

REF=input()

for i in range (4):
    if (REF != data_name[n]):
        n+=1
        cnt+=1
        if (cnt == 5):
            print("NOT FOUND, TRY OTHER NAME")

    else:
        print("E-mail address: ",data_add[n])

        break
 
